### ISSUE TITLE
usage: screenshot_to_mesh.py [-h] image_file screenshot_to_mesh.py: error: the following arguments are required: image_file

### ISSUE THREAD

**Issue by HasanthaKarunachandra** [edent/3D-Screenshot-to-3D-Model#6]
what is this error?
usage: screenshot_to_mesh.py [-h] image_file
screenshot_to_mesh.py: error: the following arguments are required: image_file

**Comment by edent** [comment]
As per the README - you need to pass it the path to an image. You can find sample images on https://shkspr.mobi/blog/2018/04/reconstructing-3d-models-from-the-last-jedi/

**Comment by saumyaparikh** [comment]
Did you find any solution to that error I am getting the same error

**Comment by edent** [comment]
What image file are you using?

**Comment by edent** [comment]
What's the exact command you are running in the terminal?

**Comment by edent** [comment]
Did you read the README?

It says

> Usage
> `python3 screenshot_to_mesh.py screenshot.png`

So you need to have an image file in the same directory as the Python file.  I have included some in the samples folder. Copy one to the same directory as your Python file and run the code. For example:

`python3 screenshot_to_mesh.py Amazing_Spiderman_1.png`

**Comment by saumyaparikh** [comment]
No module named 'pandas'
 I have installed pip install pandas then too it showing error
I am using python 3.10.0
