### ISSUE TITLE
Image mogrify

### ISSUE THREAD

**Issue by piyushkp03** [edent/3D-Screenshot-to-3D-Model#7]

**Comment by edent** [comment]
Can you post a copy of your screenshot here?

**Comment by piyushkp03** [comment]
![IMG-20220211-WA0007](https://user-images.githubusercontent.com/66120467/153588153-d08c8d11-d095-4de6-b74d-b0a9d0b6ccd2.jpg)
mogrify -crop 50%x100% +repage screenshot.png
mogrify -resize 200%x100% screenshot-*.*
Applied this command on above image

**Comment by edent** [comment]
That isn't a screenshot from a 3D movie.

You need an image like this:

<img src="https://raw.githubusercontent.com/edent/3D-Screenshot-to-3D-Model/master/samples/Finding_Nemo_01.png" alt="A screenshot from Finding Nemo."/>

**Comment by piyushkp03** [comment]
![IMG-20220212-WA0001](https://user-images.githubusercontent.com/66120467/153720112-0a6704f4-5f51-4b5c-9939-faa6eb5ea0b0.jpg)
This is the result of .ply file generated when I ran the file but the sample .ply which was already present in the folder it looked a 3D Model but this doesn't

**Comment by edent** [comment]
I'm afraid I don't know what's wrong with your output. My code is 4 years old - so something might have changed with one of the underlying libraries.

I try to support my code as best I can - but I don't have time to investigate what's going on with this. Sorry.
